CXX           = g++
COMPILE_FLAGS = -std=c++11 -Wall -Wextra -g
CXXFLAGS      = $(COMPILE_FLAGS)
LIBS          = 
DEL_FILE      = rm -f

OBJECTS_FUERZA_BRUTA 			= 	fuerzabruta.o \
									algoritmos.o

OBJECTS_BACKTRACKING 			= 	backtracking.o \
									algoritmos.o

OBJECTS_PROGRAMACION_DINAMICA 	=	programaciondinamica.o \
									algoritmos.o

TARGET_FUERZA_BRUTA        		= fuerzabruta
TARGET_BACKTRACKING        		= backtracking
TARGET_PROGRAMACION_DINAMICA	= programaciondinamica

all: $(TARGET_FUERZA_BRUTA) $(TARGET_BACKTRACKING) $(TARGET_PROGRAMACION_DINAMICA)

$(TARGET_FUERZA_BRUTA):  $(OBJECTS_FUERZA_BRUTA)  
	$(CXX) -o $(TARGET_FUERZA_BRUTA) $(OBJECTS_FUERZA_BRUTA) $(OBJCOMP) $(LIBS)

$(TARGET_BACKTRACKING):  $(OBJECTS_BACKTRACKING)  
	$(CXX) -o $(TARGET_BACKTRACKING) $(OBJECTS_BACKTRACKING) $(OBJCOMP) $(LIBS)

$(TARGET_PROGRAMACION_DINAMICA):  $(OBJECTS_PROGRAMACION_DINAMICA)  
	$(CXX) -o $(TARGET_PROGRAMACION_DINAMICA) $(OBJECTS_PROGRAMACION_DINAMICA) $(OBJCOMP) $(LIBS)

clean: 
	-$(DEL_FILE) $(OBJECTS_FUERZA_BRUTA)
	-$(DEL_FILE) $(OBJECTS_BACKTRACKING)
	-$(DEL_FILE) $(OBJECTS_PROGRAMACION_DINAMICA)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) $(TARGET_FUERZA_BRUTA)
	-$(DEL_FILE) $(TARGET_BACKTRACKING)
	-$(DEL_FILE) $(TARGET_PROGRAMACION_DINAMICA)

$(TARGET_FUERZA_BRUTA).o: src/$(TARGET_FUERZA_BRUTA).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_FUERZA_BRUTA).o src/$(TARGET_FUERZA_BRUTA).cpp

$(TARGET_BACKTRACKING).o: src/$(TARGET_BACKTRACKING).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_BACKTRACKING).o src/$(TARGET_BACKTRACKING).cpp

$(TARGET_PROGRAMACION_DINAMICA).o: src/$(TARGET_PROGRAMACION_DINAMICA).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_PROGRAMACION_DINAMICA).o src/$(TARGET_PROGRAMACION_DINAMICA).cpp

algoritmos.o: src/algoritmos.cpp src/algoritmos.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o algoritmos.o src/algoritmos.cpp
